"""add progress

Revision ID: 409eea2f5169
Revises: 
Create Date: 2021-06-03 20:33:48.918051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409eea2f5169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('video_name', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('hash_video', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('violations_num', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['videos_queue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    op.drop_table('videos_queue')
    # ### end Alembic commands ###
