from .health import HealthEndpoint
from .health import GalleryEndpoint
from .base import BaseEndpoint
from .users.create_user import CreateUserEndpoint
from .messages.messages import MessagesEndpoint
from .messages.message import MessageEndpoint
from .users.user import UserEndpoint
from .users.auth import AuthUserEndpoint
from .files.file import FilesEndpoint
from .files.file import GetFileEndpoint
from .files.file import GetProgressEndpoint
from .files.file import GetListVideosEndpoint
